name: CI • Test, Secure, Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies and tools
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest bandit pip-audit

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Bandit (Python SAST)
        run: bandit -r app

      - name: pip-audit (Python dependencies)
        run: pip-audit -r app/requirements.txt

  build-scan-and-push:
    runs-on: ubuntu-latest
    needs: test-and-secure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/medops:latest -f deploy/docker/Dockerfile .

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/medops:latest
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: '1'  
          format: table

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/medops:latest
